package com.kdp.golf.game;

import com.kdp.golf.game.db.GameRepository;
import com.kdp.golf.game.model.Game;
import com.kdp.golf.game.model.Player;
import com.kdp.golf.user.User;
import org.jdbi.v3.sqlobject.transaction.Transaction;

public class GameService
{
    private final GameRepository gameRepository;

    public GameService(GameRepository gameRepository)
    {
        this.gameRepository = gameRepository;
    }

    @Transaction
    public Game createGame(User user)
    {
        var player = Player.from(user);
        var game = Game.create(null, player); // the id will be generated by the database
        return gameRepository.create(game);
    }
}
